/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param to The number the message was sent to. Numbers are specified in E.164 format.
 * @param messageId The ID of the message
 * @param status The status of the message. See [Troubleshooting Failed SMS](/messaging/sms/guides/troubleshooting-sms).
 * @param remainingBalance Your estimated remaining balance
 * @param messagePrice The estimated cost of the message
 * @param network The estimated ID of the network of the recipient
 * @param clientRef If a `client-ref` was included when sending the SMS, this field will be included and hold the value that was sent.
 * @param accountRef **Advanced**: An optional string used to identify separate accounts using the SMS endpoint for billing purposes. To use this feature, please email [support](mailto:${CUSTOMER_SUPPORT_EMAIL})
 */
@Serializable

data class Message (

    /* The number the message was sent to. Numbers are specified in E.164 format. */
    @SerialName(value = "to") val to: kotlin.String? = null,

    /* The ID of the message */
    @SerialName(value = "message-id") val messageId: kotlin.String? = null,

    /* The status of the message. See [Troubleshooting Failed SMS](/messaging/sms/guides/troubleshooting-sms). */
    @SerialName(value = "status") val status: kotlin.String? = null,

    /* Your estimated remaining balance */
    @SerialName(value = "remaining-balance") val remainingBalance: kotlin.String? = null,

    /* The estimated cost of the message */
    @SerialName(value = "message-price") val messagePrice: kotlin.String? = null,

    /* The estimated ID of the network of the recipient */
    @SerialName(value = "network") val network: kotlin.String? = null,

    /* If a `client-ref` was included when sending the SMS, this field will be included and hold the value that was sent. */
    @SerialName(value = "client-ref") val clientRef: kotlin.String? = null,

    /* **Advanced**: An optional string used to identify separate accounts using the SMS endpoint for billing purposes. To use this feature, please email [support](mailto:${CUSTOMER_SUPPORT_EMAIL}) */
    @SerialName(value = "account-ref") val accountRef: kotlin.String? = null

) {


}

