/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.apis.DefaultApi
import org.openapitools.client.models.SendAnSms200Response
import org.openapitools.client.models.SendAnSms200Response1

class DefaultApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of DefaultApi
        //val apiInstance = DefaultApi()

        // to test sendAnSms
        should("test sendAnSms") {
            // uncomment below to test sendAnSms
            //val format : kotlin.String = json // kotlin.String | The format of the response
            //val apiKey : kotlin.String = apiKey_example // kotlin.String | Your API key
            //val from : kotlin.String = from_example // kotlin.String | The name or number the message should be sent from. Alphanumeric senderID's are not supported in all countries, see [Global Messaging](/messaging/sms/guides/global-messaging#country-specific-features) for more details. If alphanumeric, spaces will be ignored. Numbers are specified in E.164 format.
            //val to : kotlin.String = to_example // kotlin.String | The number that the message should be sent to. Numbers are specified in E.164 format.
            //val apiSecret : kotlin.String = apiSecret_example // kotlin.String | Your API secret. Required unless `sig` is provided
            //val sig : kotlin.String = sig_example // kotlin.String | The hash of the request parameters in alphabetical order, a timestamp and the signature secret. See [Signing Requests](/getting-started/concepts/signing-messages) for more details.
            //val text : kotlin.String = text_example // kotlin.String | The body of the message being sent. If your message contains characters that can be encoded according to the GSM Standard and Extended tables then you can set the `type` to `text`. If your message contains characters outside this range, then you will need to set the `type` to `unicode`.
            //val ttl : kotlin.Int = 56 // kotlin.Int | **Advanced**: The duration in milliseconds the delivery of an SMS will be attempted. By default Vonage attempts delivery for 72 hours, however the maximum effective value depends on the operator and is typically 24 - 48 hours. We recommend this value should be kept at its default or at least 30 minutes.
            //val statusReportReq : kotlin.Boolean = true // kotlin.Boolean | **Advanced**: Boolean indicating if you like to receive a [Delivery Receipt](/messaging/sms/building-blocks/receive-a-delivery-receipt).
            //val paramCallback : kotlin.String = paramCallback_example // kotlin.String | **Advanced**: The webhook endpoint the delivery receipt for this sms is sent to. This parameter overrides the webhook endpoint you set in Dashboard. Max 100 characters.
            //val messageClass : kotlin.Int = 56 // kotlin.Int | **Advanced**: The Data Coding Scheme value of the message
            //val type : kotlin.String = type_example // kotlin.String | **Advanced**: The format of the message body
            //val body : kotlin.String = body_example // kotlin.String | **Advanced**: Hex encoded binary data. Depends on `type` parameter having the value `binary`.
            //val udh : kotlin.String = udh_example // kotlin.String | **Advanced**: Your custom Hex encoded [User Data Header](https://en.wikipedia.org/wiki/User_Data_Header). Depends on `type` parameter having the value `binary`.
            //val protocolId : kotlin.Int = 56 // kotlin.Int | **Advanced**: The value of the [protocol identifier](https://en.wikipedia.org/wiki/GSM_03.40#Protocol_Identifier) to use. Ensure that the value is aligned with `udh`.
            //val clientRef : kotlin.String = clientRef_example // kotlin.String | **Advanced**: You can optionally include your own reference of up to 100 characters.
            //val accountRef : kotlin.String = accountRef_example // kotlin.String | **Advanced**: An optional string used to identify separate accounts using the SMS endpoint for billing purposes. To use this feature, please email [support](mailto:${CUSTOMER_SUPPORT_EMAIL})
            //val entityId : kotlin.String = entityId_example // kotlin.String | **Advanced**: A string parameter that satisfies regulatory requirements when sending an SMS to specific countries. For more information please refer to the [Country-Specific Outbound SMS Features](https://api.support.vonage.com/hc/en-us/articles/115011781468)
            //val contentId : kotlin.String = contentId_example // kotlin.String | **Advanced**: A string parameter that satisfies regulatory requirements when sending an SMS to specific countries. For more information please refer to the [Country-Specific Outbound SMS Features](https://api.support.vonage.com/hc/en-us/articles/115011781468)
            //val result : SendAnSms200Response = apiInstance.sendAnSms(format, apiKey, from, to, apiSecret, sig, text, ttl, statusReportReq, paramCallback, messageClass, type, body, udh, protocolId, clientRef, accountRef, entityId, contentId)
            //result shouldBe ("TODO")
        }

    }
}
