/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param msisdn The number the message was sent to. Numbers are specified in E.164 format.
 * @param to The SenderID you set in `from` in your request.
 * @param networkCode The Mobile Country Code Mobile Network Code (MCCMNC) of the carrier this phone number is registered with.
 * @param messageId The Vonage ID for this message.
 * @param price The cost of the message
 * @param status A code that explains where the message is in the delivery process.
 * @param scts When the DLR was received from the carrier in the following format `YYMMDDHHMM`. For example, `2001011400` is at `2020-01-01 14:00`
 * @param errCode The status of the request. Will be a non `0` value if there has been an error, or if the status is unknown. See the [Delivery Receipt documentation](/messaging/sms/guides/delivery-receipts#dlr-error-codes) for more details
 * @param apiKey The API key that sent the SMS. This is useful when multiple accounts are sending webhooks to the same endpoint.
 * @param messageTimestamp The time when Vonage started to push this Delivery Receipt to your webhook endpoint.
 */
@Serializable

data class DeliveryReceipt (

    /* The number the message was sent to. Numbers are specified in E.164 format. */
    @SerialName(value = "msisdn") val msisdn: kotlin.String? = null,

    /* The SenderID you set in `from` in your request. */
    @SerialName(value = "to") val to: kotlin.String? = null,

    /* The Mobile Country Code Mobile Network Code (MCCMNC) of the carrier this phone number is registered with. */
    @SerialName(value = "network-code") val networkCode: kotlin.String? = null,

    /* The Vonage ID for this message. */
    @SerialName(value = "messageId") val messageId: kotlin.String? = null,

    /* The cost of the message */
    @SerialName(value = "price") val price: kotlin.String? = null,

    /* A code that explains where the message is in the delivery process. */
    @SerialName(value = "status") val status: kotlin.String? = null,

    /* When the DLR was received from the carrier in the following format `YYMMDDHHMM`. For example, `2001011400` is at `2020-01-01 14:00` */
    @SerialName(value = "scts") val scts: kotlin.String? = null,

    /* The status of the request. Will be a non `0` value if there has been an error, or if the status is unknown. See the [Delivery Receipt documentation](/messaging/sms/guides/delivery-receipts#dlr-error-codes) for more details */
    @SerialName(value = "err-code") val errCode: kotlin.String? = null,

    /* The API key that sent the SMS. This is useful when multiple accounts are sending webhooks to the same endpoint. */
    @SerialName(value = "api-key") val apiKey: kotlin.String? = null,

    /* The time when Vonage started to push this Delivery Receipt to your webhook endpoint. */
    @SerialName(value = "message-timestamp") val messageTimestamp: kotlin.String? = null

) {


}

