/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param status The error status of the message
 * @param errorText The description of the error
 */
@Serializable

data class ErrorMessage (

    /* The error status of the message */
    @SerialName(value = "status") val status: kotlin.String? = null,

    /* The description of the error */
    @SerialName(value = "error-text") val errorText: kotlin.String? = null

) {


}

