/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.Message

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Message sent
 *
 * @param messageCount The amount of messages in the request
 * @param messages 
 */
@Serializable

data class SMS (

    /* The amount of messages in the request */
    @SerialName(value = "message-count") val messageCount: kotlin.String? = null,

    @SerialName(value = "messages") val messages: kotlin.collections.List<Message>? = null

) {


}

