/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.ErrorMessage

class ErrorMessageTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ErrorMessage
        //val modelInstance = ErrorMessage()

        // to test the property `status` - The error status of the message
        should("test status") {
            // uncomment below to test the property
            //modelInstance.status shouldBe ("TODO")
        }

        // to test the property `errorText` - The description of the error
        should("test errorText") {
            // uncomment below to test the property
            //modelInstance.errorText shouldBe ("TODO")
        }

    }
}
