/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.SendAnSms200Response1
import org.openapitools.client.models.ErrorMessage
import org.openapitools.client.models.ErrorXml
import org.openapitools.client.models.SMSXml

class SendAnSms200Response1Test : ShouldSpec() {
    init {
        // uncomment below to create an instance of SendAnSms200Response1
        //val modelInstance = SendAnSms200Response1()

        // to test the property `messages`
        should("test messages") {
            // uncomment below to test the property
            //modelInstance.messages shouldBe ("TODO")
        }

    }
}
