/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.Error
import org.openapitools.client.models.ErrorMessage

class ErrorTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of Error
        //val modelInstance = Error()

        // to test the property `messageCount` - The amount of messages in the request
        should("test messageCount") {
            // uncomment below to test the property
            //modelInstance.messageCount shouldBe ("TODO")
        }

        // to test the property `messages`
        should("test messages") {
            // uncomment below to test the property
            //modelInstance.messages shouldBe ("TODO")
        }

    }
}
