/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.Message

class MessageTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of Message
        //val modelInstance = Message()

        // to test the property `to` - The number the message was sent to. Numbers are specified in E.164 format.
        should("test to") {
            // uncomment below to test the property
            //modelInstance.to shouldBe ("TODO")
        }

        // to test the property `messageId` - The ID of the message
        should("test messageId") {
            // uncomment below to test the property
            //modelInstance.messageId shouldBe ("TODO")
        }

        // to test the property `status` - The status of the message. See [Troubleshooting Failed SMS](/messaging/sms/guides/troubleshooting-sms).
        should("test status") {
            // uncomment below to test the property
            //modelInstance.status shouldBe ("TODO")
        }

        // to test the property `remainingBalance` - Your estimated remaining balance
        should("test remainingBalance") {
            // uncomment below to test the property
            //modelInstance.remainingBalance shouldBe ("TODO")
        }

        // to test the property `messagePrice` - The estimated cost of the message
        should("test messagePrice") {
            // uncomment below to test the property
            //modelInstance.messagePrice shouldBe ("TODO")
        }

        // to test the property `network` - The estimated ID of the network of the recipient
        should("test network") {
            // uncomment below to test the property
            //modelInstance.network shouldBe ("TODO")
        }

        // to test the property `clientRef` - If a `client-ref` was included when sending the SMS, this field will be included and hold the value that was sent.
        should("test clientRef") {
            // uncomment below to test the property
            //modelInstance.clientRef shouldBe ("TODO")
        }

        // to test the property `accountRef` - **Advanced**: An optional string used to identify separate accounts using the SMS endpoint for billing purposes. To use this feature, please email [support](mailto:${CUSTOMER_SUPPORT_EMAIL})
        should("test accountRef") {
            // uncomment below to test the property
            //modelInstance.accountRef shouldBe ("TODO")
        }

    }
}
